### PR TITLE
Added shouldPass validation

### PR DESCRIPTION
**Pull request by anotherpit**
Hi, @ganeshrvel! Thanks for the library. I love its Flutter- and UI-agnostic design and composability of the rules. Plays really well with state management in my project. The only thing I was missing was ability to use my own custom validation functions for some not-so-typical checks. So here goes the pull request with this feature.

### CODE REVIEW

**Comment by ganeshrvel** [comment]
Wow.. let me check this.


Thank you!!

**Comment by anotherpit** [comment]
@ganeshrvel Are there any news on this?

**Comment by ganeshrvel** [comment]
Hi, @anotherpit  i have reviewed your pr. Could you edit the merge branch from `master` to `release/2.0.0`? I have release the version update after a few more cleanup.

Thanks for the PR.!

**Comment by anotherpit** [comment]
@ganeshrvel OK, I've switched the base to `release/2.0.0`, but didn't merge any of your changes to my branch yet, and didn't rerun tests. If you're OK to merge it as is, that's fine. Otherwise I'll give it a look later.

**Comment by ganeshrvel** [comment]
It's just README updates in this branch. I will merge!

**Pull request merged**
